//Function Declaration
void helloWorld();
void input_output();
void power();
void intDataType();
void charDataType();
void escapeSequence();
void boolDataType();
void floatingPointDataType();
void constants();